### ISSUE TITLE
Incorrect code being generated when LSP is enabled

### ISSUE THREAD

**Issue by legendofmiracles** [pta2002/nixvim#7] opened 2021-12-14 00:46 UTC
```lua
-- LSP {{{
local __lspServers = {'rnix','rust_analyzer'}
local __lspOnAttach = function(client)

end
local __lspCapabilities = function

end

for i,server in ipairs(__lspServers) do
  if type(server) == "string" then
    require('lspconfig')[server].setup {
      on_attach = __lspOnAttach
      capabilities = __lspCapabilities
    }
  else
    require('lspconfig')[server.name].setup(server.extraOptions)
  end
end
-- }}}
```
here's all the generated code.

With this config:
```nix
plugins.lsp = {
  enable = true;
  servers = {
    rust-analyzer.enable = true;
    rnix-lsp.enable = true;
  };
};
```

Whenever I open vim it shows me this error, and doesn't load any of my lua config:
```
Error detected while processing /home/nix/.config/nvim/init.vim:
line  127:
E5107: Error loading lua [string ":lua"]:8: '(' expected near 'end'
```

Any help would be appreciated

Cheers

**Comment by pta2002** [comment] 2021-12-14 12:30
Oh, I think I need to fix the __lspCapabilities function (it's missing the
parentheses). I can take care of this later tonight.

legendofmiracles ***@***.***> escreveu no dia terça,
14/12/2021 à(s) 00:47:

**Comment by legendofmiracles** [comment] 2021-12-14 17:09
> I've added the parentheses to the __lspCapabilities function but that doesn't fix the problem (`E5107: Error loading lua [string ":lua"]:14: '}' expected (to close '{' at line 12) near 'capabilities'`)
> 
> 
> 
> EDIT: It seems like there are some `,` missing
> 
> ```lua
> 
> -- LSP {{{
> 
> local __lspServers = {}
> 
> local __lspOnAttach = function(client)
> 
> 
> 
> end
> 
> 
> 
> local __lspCapabilities = function()
> 
> 
> 
> end
> 
> for i,server in ipairs(__lspServers) do
> 
>   if type(server) == "string" then
> 
>     require('lspconfig')[server].setup {
> 
>       on_attach = __lspOnAttach
> 
>       capabilities = __lspCapabilities
> 
>     }
> 
>   else
> 
>     require('lspconfig')[server.name].setup(server.extraOptions)
> 
>   end
> 
> end
> 
> -- }}}
> 
> ```

Could you open a PR with your fix?

**Comment by Builditluc** [comment] 2021-12-14 17:10
> Could you open a PR with your fix?

yes, #8

**Comment by pta2002** [comment] 2021-12-14 17:20
Fixed by #8, thank you!

**Comment by legendofmiracles** [comment] 2021-12-14 18:35
I should maybe open another issue, but this is still fresh 😄 

The nix lsp seems to be broken:
```
Error detected while processing FileType Autocommands for "nix":
E5108: Error executing lua vim/shared.lua:260: after the second argument: expected table, got function
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:260: in function 'tbl_deep_extend'
        ...e-manager/start/nvim-lspconfig/lua/lspconfig/configs.lua:134: in function '_make_config'
        ...home-manager/start/nvim-lspconfig/lua/lspconfig/util.lua:255: in function 'add'
        ...e-manager/start/nvim-lspconfig/lua/lspconfig/configs.lua:217: in function 'try_add'
        [string ":lua"]:1: in main chunk

```

**Comment by Builditluc** [comment] 2021-12-14 20:19
did you use the nix lsp (rnix) or nix language support?

**Comment by pta2002** [comment] 2021-12-15 00:16
I'll be checking this out tomorrow, thanks for reporting. From what I remember, no plugins should conflict at all, so it's definitely a bug.

**Comment by Builditluc** [comment] 2021-12-15 16:46
> Actually, while I'm not getting errors with rnix-lsp (but it doesn't appear to be working) when the nix plugin is disabled. I am getting it for rust, with the nix plugin disabled:
> 
> ```
> Error detected while processing FileType Autocommands for "rust":
> E5108: Error executing lua vim/shared.lua:260: after the second argument: expected table, got function
> stack traceback:
>         [C]: in function 'error'
>         vim/shared.lua:608: in function 'validate'
>         vim/shared.lua:260: in function 'tbl_deep_extend'
>         ...e-manager/start/nvim-lspconfig/lua/lspconfig/configs.lua:134: in function '_make_config'
>         ...home-manager/start/nvim-lspconfig/lua/lspconfig/util.lua:255: in function 'add'
>         ...e-manager/start/nvim-lspconfig/lua/lspconfig/configs.lua:217: in function 'try_add'
>         [string ":lua"]:1: in main chunk
> ```

that's weird because i can't seem to reproduce the error you're getting when enabling `plugins.nix` and `plugins.lsp.servers.rnix-lsp`

**Comment by pta2002** [comment] 2022-01-01 13:34
Hi, sorry for being gone for so long. Seems like there are several issues to unravel here! First off, after turning on LSP on my config, I get this line:

```lua
local __lspCapabilities = function
  
end
```

in my init.vim, which is clearly wrong, because it's missing the parentheses after function().

However, looking at the culprit code...

```nix
      extraConfigLua = ''
        -- LSP {{{
        local __lspServers = ${helpers.toLuaObject cfg.enabledServers}
        local __lspOnAttach = function(client)
          ${cfg.onAttach}
        end
        local __lspCapabilities = function()
          ${cfg.capabilities}
        end
        -- ...
     "; 
```

Uh, this is odd.... If anyone has any idea why this is happening, help is welcome!

**Comment by pta2002** [comment] 2022-01-01 13:36
For now, just to have LSP working, I think I will just comment this part out, since it's not being used by anyone.

**Closed** 2022-01-18 13:18 UTC
Labels: bug
