### ISSUE TITLE
Config isn't honored/loaded + config parsing issues

### ISSUE THREAD

**Issue by Church-** [pta2002/nixvim#105] opened 2023-01-08 05:52 UTC
**Nixpkgs channel**: Version 22.11

## Description
When using the nixos module and generating a config at /etc/nvim/sysinit.lua I would expect the settings to be honored when I open nvim.

However no settings are loaded when I open nvim.
If I directly open nvim with the config file via `nvim -u /etc/nvim/sysinit.lua` I do get lua parsing errors.

The first error is:
```
Error detected while processing /etc/nvim/sysinit.lua:
E5113: Error while calling lua chunk: /etc/nvim/sysinit.lua:10: invalid value for option
stack traceback:
        [C]: in function '__newindex'
        /etc/nvim/sysinit.lua:10: in main chunk
```
which seems to relate to commit hash `4ddd3969`

If you change L10 from `vim.o[k] = v` to `vim.opt[k] = v` we make it pass this error.

The next error once we reload nvim with the fixed config is:
```
Error detected while processing /tmp/sysinit.lua:
E5113: Error while calling lua chunk: /tmp/sysinit.lua:61: module 'lspconfig' not found:
        no field package.preload['lspconfig']
        no file '/nix/store/xnxyn0bp80pf2jk58a72za679ajlcp32-luajit-2.1.0-2022-10-04-env/share/lua/5.1/lspconfig.lua'
        no file '/nix/store/xnxyn0bp80pf2jk58a72za679ajlcp32-luajit-2.1.0-2022-10-04-env/share/lua/5.1/lspconfig/init.lua'
        no file '/nix/store/xnxyn0bp80pf2jk58a72za679ajlcp32-luajit-2.1.0-2022-10-04-env/lib/lua/5.1/lspconfig.so'
stack traceback:
        [C]: in function 'require'
        /tmp/sysinit.lua:61: in main chunk
```

Which I assume is from not having access to the set of 
plugins, vim runtime, etc in some manner.

## Config
```
{ pkgs, config, ... }:

{
  programs = {
    nixvim = {
      enable = true;
      viAlias = true;
      vimAlias = true;
      options = {
        mouse = "a";
        termguicolors = true;
        background = "dark";
        ignorecase = true;
        swapfile = false;
        showmatch = true;
        hlsearch = true;
        wildmode = [ "longest" "list" ];
        expandtab = true;
        tabstop = 4;
        shiftwidth = 4;
      };
      extraConfigVim = ''
        set completeopt=menuone,noinsert,noselect
        set shortmess+=c
        set whichwrap+=<,>,h,l,[,]
        au BufRead,BufNewFile *.md setlocal textwidth=80
        au BufRead,BufNewFile *.yaml setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.yml setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.sls setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.sh setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.nix setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.js setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.ts setlocal textwidth=80 shiftwidth=2 cc=80
        au BufRead,BufNewFile *.lua setlocal textwidth=80 shiftwidth=2 cc=80                                                    
        au BufRead,BufNewFile *.py setlocal textwidth=80 shiftwidth=4 cc=88                                                     
        au BufRead,BufNewFile *.rs setlocal textwidth=80 shiftwidth=4 cc=80
        au BufRead,BufNewFile *.c setlocal textwidth=80 shiftwidth=4 cc=80
        au BufRead,BufNewFile *.go setlocal textwidth=80 shiftwidth=4 cc=80
        au BufWrite *.rs :Autoformat
        au BufWrite *.nix :Autoformat
      '';
      plugins = {
        lsp = {
          enable = true;
          servers = {
            rnix-lsp = { enable = true; };
            rust-analyzer = { enable = true; };
          };
        };
      };
    };
  };
}
```

**Comment by pta2002** [comment] 2023-01-08 12:22
What Neovim version are you on? `vim.o` not working is odd

**Comment by Church-** [comment] 2023-01-08 19:05
Version 0.7 I believe.

**Comment by Church-** [comment] 2023-01-09 11:25
Okay I had a default nvim package in systemPackages overriding the nixvim package.

Removed that and rebuilt, now on nvim version 0.8.1 but still seeing the same issues as above.

**Comment by Church-** [comment] 2023-01-09 19:58
Okay so seems to be mostly a red herring.

The issue with 
```
Error detected while processing /etc/nvim/sysinit.lua:
E5113: Error while calling lua chunk: /etc/nvim/sysinit.lua:10: invalid value for option
stack traceback:
        [C]: in function '__newindex'
        /etc/nvim/sysinit.lua:10: in main chunk
```
was due to having improper options in my nix config.

The second error with not loading the LSP config also went away once fixed my vim config options and loaded the config via the -u param.

However this still doesn't answer the question as to why I can't load the config file located at /etc/nvim/sysinit.lua by default?

I can only assume it's not a default file search path for neovim?

**Comment by Church-** [comment] 2023-01-09 20:00
One could make the patch to nixvim to always pass -u /etc/nvim/sysinit.lua to neovim?

**Comment by Church-** [comment] 2023-01-10 01:01
From reading over the nvim source code, while we can check multiple dirs including /etc/nvim/ for vim configs I don't believe this holds for sysinit.lua. So this module may be broken.

A workaround seems to be to use `wrapRc = true;` for now however.

**Comment by pta2002** [comment] 2023-01-10 12:41
I'm assuming yes, unfortunately it doesn't seem to look at sysinit.lua by default (as far as I can tell, it _does_ look at sysinit.vim)

I'd say the best course of action here would actually be to generate a `sysinit.vim` for this case. Short term though, don't see anything wrong with just making `wrapRc = true`.

**Comment by Church-** [comment] 2023-01-12 03:11
So seems we should do a stub sysinit.vim and do a lua call to load the systinit.lua file then?

Or should we just revert to writing a vim file again?

**Comment by GaetanLepage** [comment] 2023-01-17 17:25
I think that your problem is caused by the line `wildmode = [ "longest" "list" ];` in the options.
Indeed, I had the same message when using `programs.nixvim.options.completeopt = [ "menu" "menuone" "noselect" ];`.
I have since then switched to `programs.nixvim.options.completeopt = "menu,menuone,noselect";` and it works fine.

**Comment by Church-** [comment] 2023-01-17 18:47
Yeah that was my issue wrt config parsing.

But not wrt the config being loaded or attempted to load afaic.

**Comment by pta2002** [comment] 2023-01-25 18:54
> I think that your problem is caused by the line `wildmode = [ "longest" "list" ];` in the options. Indeed, I had the same message when using `programs.nixvim.options.completeopt = [ "menu" "menuone" "noselect" ];`. I have since then switched to `programs.nixvim.options.completeopt = "menu,menuone,noselect";` and it works fine.

hm that seems like a bug that needs to be fixed, but seems like it might be an upstream thing (because it doesn't work when setting it to an array)

**Comment by GaetanLepage** [comment] 2023-05-04 13:55
Hasn't this gotten fixed by https://github.com/pta2002/nixvim/pull/167 ?

**Closed** 2023-05-08 12:49 UTC
Labels: bug
