### ISSUE TITLE
Unable to configure properly - a unknow reason for all version 

### ISSUE THREAD

**Issue by jackyliu16** [pta2002/nixvim#296] opened 2023-03-27 01:01 UTC
**Plugin affected**: magma-nvim-goose (a plugins using for jupyter but wasn't add by me)
**Nixpkgs channel**: 
home-manager https://github.com/nix-community/home-manager/archive/release-22.11.tar.gz
nixpkgs https://mirrors.tuna.tsinghua.edu.cn/nix-channels/nixpkgs-unstable 
**Home-manager version**: 22.11

## Description
A problem shows in home-manager switch, it asking for a unknow plugins `magma-nvim-goose`, i have trying to reset my nixvim configuration to oldest version but the problem haven't been solved.
```
➜  nixpkgs git:(mynixvim) ✗ hns --show-trace
error:
       … while evaluating the attribute 'activationPackage'

       at /home/jacky/.nix-defexpr/channels/home-manager/modules/default.nix:54:3:

           53|
           54|   activationPackage = module.config.home.activationPackage;
             |   ^
           55|

       … while evaluating call site

       at /home/jacky/.nix-defexpr/channels/home-manager/modules/default.nix:39:12:

           38|
           39|   module = showWarnings (
             |            ^
           40|     let

       … while calling 'showWarnings'

       at /home/jacky/.nix-defexpr/channels/home-manager/modules/default.nix:18:18:

           17|
           18|   showWarnings = res:
             |                  ^
           19|     let

       … while evaluating call site

       at /home/jacky/.nix-defexpr/channels/home-manager/modules/default.nix:22:7:

           21|     in
           22|       fold f res res.config.warnings;
             |       ^
           23|

       … while calling 'foldr'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/lists.nix:53:20:

           52|   */
           53|   foldr = op: nul: list:
             |                    ^
           54|     let

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/lists.nix:60:8:

           59|         else op (elemAt list n) (fold' (n + 1));
           60|     in fold' 0;
             |        ^
           61|

       … while calling 'fold''

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/lists.nix:56:15:

           55|       len = length list;
           56|       fold' = n:
             |               ^
           57|         if n == len

       … while evaluating call site

       at /home/jacky/.nix-defexpr/channels/home-manager/modules/default.nix:41:16:

           40|     let
           41|       failed = collectFailed rawModule.config;
             |                ^
           42|       failedStr = concatStringsSep "\n" (map (x: "- ${x}") failed);

       … while calling 'collectFailed'

       at /home/jacky/.nix-defexpr/channels/home-manager/modules/default.nix:15:19:

           14|
           15|   collectFailed = cfg:
             |                   ^
           16|     map (x: x.message) (filter (x: !x.assertion) cfg.assertions);

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling 'g'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/attrsets.nix:535:19:

          534|           g =
          535|             name: value:
             |                   ^
          536|             if isAttrs value && cond value

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/attrsets.nix:538:20:

          537|               then recurse (path ++ [name]) value
          538|               else f (path ++ [name]) value;
             |                    ^
          539|         in mapAttrs g;

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:270:72:

          269|           # For definitions that have an associated option
          270|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          271|

       … while evaluating the attribute 'value'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:728:9:

          727|     in warnDeprecation opt //
          728|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          729|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `assertions':

       … while evaluating the attribute 'mergedValue'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:763:5:

          762|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          763|     mergedValue =
             |     ^
          764|       if isDefined then

       … while evaluating the attribute 'values'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:757:9:

          756|       in {
          757|         values = defs''';
             |         ^
          758|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:856:7:

          855|     in {
          856|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          857|       inherit highestPrio;

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:743:17:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                 ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:743:28:

          742|         # Process mkMerge and mkIf properties.
          743|         defs' = concatMap (m:
             |                            ^
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/home/jacky/.config/nixpkgs/vimAndNeovim/nixvim.nix':

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:744:137:

          743|         defs' = concatMap (m:
          744|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          745|         ) defs;

       … while calling 'dischargeProperties'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:815:25:

          814|   */
          815|   dischargeProperties = def:
             |                         ^
          816|     if def._type or "" == "merge" then

       … while evaluating the attribute 'condition'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:886:14:

          885|     { _type = "if";
          886|       inherit condition content;
             |              ^
          887|     };

       … while evaluating the attribute 'condition'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:886:14:

          885|     { _type = "if";
          886|       inherit condition content;
             |              ^
          887|     };

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling 'g'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/attrsets.nix:535:19:

          534|           g =
          535|             name: value:
             |                   ^
          536|             if isAttrs value && cond value

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/attrsets.nix:538:20:

          537|               then recurse (path ++ [name]) value
          538|               else f (path ++ [name]) value;
             |                    ^
          539|         in mapAttrs g;

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:270:72:

          269|           # For definitions that have an associated option
          270|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          271|

       … while evaluating the attribute 'value'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:728:9:

          727|     in warnDeprecation opt //
          728|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          729|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `programs.nixvim':

       … while evaluating the attribute 'mergedValue'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:763:5:

          762|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          763|     mergedValue =
             |     ^
          764|       if isDefined then

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:765:59:

          764|       if isDefined then
          765|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          766|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while calling 'merge'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/types.nix:742:22:

          741|         check = x: isAttrs x || isFunction x || path.check x;
          742|         merge = loc: defs:
             |                      ^
          743|           (base.extendModules {

       … while evaluating the attribute 'config'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:346:9:

          345|         options = checked options;
          346|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          347|         _module = checked (config._module);

       … while evaluating the attribute 'unmatchedDefns'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:640:7:

          639|       # Transforms unmatchedDefnsByName into a list of definitions
          640|       unmatchedDefns =
             |       ^
          641|         if configs == []

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/attrsets.nix:479:10:

          478|     attrs:
          479|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          480|

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/attrsets.nix:479:16:

          478|     attrs:
          479|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          480|

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:647:46:

          646|         else
          647|           concatLists (mapAttrsToList (name: defs:
             |                                              ^
          648|             map (def: def // {

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:633:22:

          632|         # Propagate all unmatched definitions from nested option sets
          633|         mapAttrs (n: v: v.unmatchedDefns) resultsByName
             |                      ^
          634|         # Plus the definitions for the current prefix that don't have a matching option

       … while evaluating the attribute 'unmatchedDefns'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:640:7:

          639|       # Transforms unmatchedDefnsByName into a list of definitions
          640|       unmatchedDefns =
             |       ^
          641|         if configs == []

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/attrsets.nix:479:10:

          478|     attrs:
          479|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          480|

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/attrsets.nix:479:16:

          478|     attrs:
          479|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          480|

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:647:46:

          646|         else
          647|           concatLists (mapAttrsToList (name: defs:
             |                                              ^
          648|             map (def: def // {

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:633:22:

          632|         # Propagate all unmatched definitions from nested option sets
          633|         mapAttrs (n: v: v.unmatchedDefns) resultsByName
             |                      ^
          634|         # Plus the definitions for the current prefix that don't have a matching option

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:587:39:

          586|
          587|       resultsByName = mapAttrs (name: decls:
             |                                       ^
          588|         # We're descending into attribute ‘name’.

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:593:33:

          592|           defns' = defnsByName'.${name} or [];
          593|           optionDecls = filter (m: isOption m.options) decls;
             |                                 ^
          594|         in

       … while evaluating call site

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:593:36:

          592|           defns' = defnsByName'.${name} or [];
          593|           optionDecls = filter (m: isOption m.options) decls;
             |                                    ^
          594|         in

       … while calling 'isType'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/types.nix:70:18:

           69| rec {
           70|   isType = type: x: (x._type or "") == type;
             |                  ^
           71|

       … while evaluating the attribute 'options'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/lib/modules.nix:560:38:

          559|       declsByName = byName "options" (module: option:
          560|           [{ inherit (module) _file; options = option; }]
             |                                      ^
          561|         ) options;

       … while evaluating the attribute 'vimPlugins.magma-nvim-goose'

       at /nix/store/3vf1f4q1k0r57ix1ly1b47rkb1rcaais-nixpkgs/nixpkgs/pkgs/top-level/all-packages.nix:38472:3:

        38471|
        38472|   vimPlugins = recurseIntoAttrs (callPackage ../applications/editors/vim/plugins {
             |   ^
        38473|     llvmPackages = llvmPackages_6;

       error: attribute 'magma-nvim-goose' missing

       at /nix/store/zvwwwc64mbxjihl6alwldznb9c1cq0fa-source/plugins/utils/magma-nvim.nix:57:15:

           56|     description = "magma-nvim";
           57|     package = pkgs.vimPlugins.magma-nvim-goose;
             |               ^
           58|     globalPrefix = "magma_";   
```

## Config
https://github.com/jackyliu16/home-manager/tree/mynixvim

**Comment by jackyliu16** [comment] 2023-03-27 02:33
It seems that the problem is being case by commit 7f50b54bfb999671778f17192d75b8c23c6d75b9, which confirm by lock the commit version.

**Comment by GaetanLepage** [comment] 2023-03-28 09:17
@jackyliu16 is it working better now that you have updated ?
If so, can I close this issue ?

**Comment by houstdav000** [comment] 2023-03-28 12:06
> Hi ! We recently have upstream the magma-nvim-goose package to nixpkgs. Hence, we now rely on it for nixvim. The nixvim flake nixpkgs input has been updated so it should be able to find the package properly.
> 
> The problem is that you are probably using a version of nixpkgs that is not recent enough. nixvim relies on the **nixos-unstable** channel. Hence, you should either use this channel system-wide or use nixvim as a flake. In the latter, nixvim will be autonomous regarding its inputs.

I suppose it is a little confusing that NixOS modules would use the configuration builder's package set, since you would think for flake-driven modules, they'd be coupled to the flake, not to the system (guess you have to think of them as overlays).

Guess I need to figure out how to set the `pkgs` arg for a single module... or if that's possible

**Comment by GaetanLepage** [comment] 2023-03-28 12:42
> I suppose it is a little confusing that NixOS modules would use the configuration builder's package set, since you would think for flake-driven modules, they'd be coupled to the flake, not to the system (guess you have to think of them as overlays).
> 
> Guess I need to figure out how to set the `pkgs` arg for a single module... or if that's possible

Actually you can do both.
By default:
```nix
inputs.nixvim.url = "github:pta2002/nixvim";
```
the nixpkgs defined in the nixvim flake will be used. So, your vim plugins will not come from the same version of nixpkgs as the one you are using system-wide.
Using this, you shouldn't have any constraint on the nixpkgs you want to use for your system. You could be running `nixos-22.11` and be perfectly fine.

However, you can force nixvim to use the same version of nixpkgs as the one you are using on your system:
```nix
inputs.nixvim = {
  url = "github:pta2002/nixvim";
  inputs.nixpkgs.follows = "nixpkgs";
};
```
In this case, your nixpkgs must be recent enough.

**Comment by GaetanLepage** [comment] 2023-03-28 12:52
Oh... I am not sure to understand.
Do we agree that in the case below, both nixvim and home-manager will use the same version of nixpkgs as your nixos install right (VERSION_A) ?
```nix
inputs = {
  nixpkgs.url = VERSION_A;
  home-manager = {
    url = "github:nix-community/home-manager";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  nixvim = {
    url = "github:pta2002/nixvim";
    inputs.nixpkgs.follows = "nixpkgs";
  };
};

```

**Closed** 2023-03-28 13:48 UTC
Labels: bug

**Comment by imMaturana** [comment] 2023-04-02 13:57
I'm on `nixpkgs-22.11` and I can reproduce the problem.

After importing the `nixvim` module through `home-manager`, the `pkgs` argument from `home-manager` is being passed to `nixvim`, prolly something like
```nix
nixpkgs.overlays = [(_: {
  magma-nvim-goose = pkgs.unstable.vimPlugins.magma-nvim-goose;
}];
```
can solve this, but seens a bit hacky. Please, correct me if I'm wrong, but issuing `input.nixpkgs.follows` line don't solves anything.

sorry about my english

**Comment by traxys** [comment] 2023-04-02 14:08
Yeah we don't really have a way setup right now to support non unstable nixpkgs. The input nixpkgs is only used in the standalone version of nixvim, in both home-manager and nixos modules the host nixpkgs is used. You could use the standalone version right now if you want to limit the unstable nixpkgs to nixvim.

There are several considerations we need to think about (nixpkgs stability, neovim stability, plugin stability) that we have not really ironed out.

**Comment by imMaturana** [comment] 2023-04-02 15:08
the backport approach, both used in nixpkgs and home-manager, can solve this, maybe that's something that could be considerable in the future

**Comment by cyntheticfox** [comment] 2023-04-02 15:19
Backporting is probably the way to go, but it might also be a decent idea to allow setting the package via an option for each of the supported plugins, or one for the whole `vimPlugins` package subset.

(Overriding `vimPlugins` via overlay was the way I got it to work in my home-manager config)

**Comment by traxys** [comment] 2023-04-02 16:18
All (most?) of the plugins have a package option to do that. The problem is that the plugin options can wildly vary between versions, and as such nixvim needs to adapt to the unstable plugins.
