### ISSUE TITLE
Treesitter - invalid node type

### ISSUE THREAD

**Issue by pupbrained** [pta2002/nixvim#102] opened 2023-01-05 22:17 UTC
**Plugin affected**:
Treesitter
**Nixpkgs channel**:
Unstable
**Home-manager version**:
Unstable

## Description
Some languages return "invalid node type" from treesitter, e.g. typescript. Others, though, work perfectly fine, and return no errors.

Trying to run treesitter with `nixGrammars = false;` returns read-only filesystem issues, and adding a custom parser directory causes treesitter to reinstall parsers every time nvim is started.

## Config
[nixvim.nix](https://github.com/pupbrained/nix-config/blob/main/pkgs/nixvim.nix)

**Comment by pta2002** [comment] 2023-01-06 11:29
I think this might be an upstream issue (TS grammars on nixpkgs not up to date), but I'll see what I can do

**Comment by pta2002** [comment] 2023-01-06 19:03
I can reproduce this issue with `nixos-unstable`, but can confirm it is _not_ present in `nixos-22.11`. I _think_ the issue is that the current treesitter grammars are made targetting nvim nightly, which isn't on nixpkgs yet (since it's still pre-release). Not really sure how to address this in nixvim; maybe we can force nixvim to use the grammars on `nixos-22.11`? Doesn't sound ideal though.

**Comment by pupbrained** [comment] 2023-01-07 01:01
I'm not sure that it is fixed with the nightly, considering I'm having the issue with nixos-unstable-small and the latest nightly of neovim using their flake.

**Comment by pta2002** [comment] 2023-01-07 07:46
I'm referring to the Neovim nightly (0.9 prerelease), not NixOS. Nvim 0.9 isn't in nixpkgs.

**Comment by pupbrained** [comment] 2023-01-07 08:10
I am aware, I was referring to the same thing. Neovim's GitHub repo has a nix flake for the nightly in the `contrib` folder.

**Comment by GaetanLepage** [comment] 2023-01-12 10:10
I can confirm this problem, for instance in bash files.

**Comment by pta2002** [comment] 2023-01-21 17:23
Seems to be fixed by #131, so I'll be closing this

**Closed by pta2002** 2023-01-21 17:23 UTC
Labels: bug
